export const stockDataCron = [
    { company: "GameStop Corp.", ticker: "GME" },
    { company: "AMC ENTERTAINMENT HOLDINGS, INC.", ticker: "AMC" },
    { company: "Tesla, Inc. Common Stock", ticker: "TSLA" },
    { company: "Palantir Technologies Inc.", ticker: "PLTR" },
    { company: "Apple Inc.", ticker: "AAPL" },
    { company: "MicroStrategy Inc", ticker: "MSTR" },
    { company: "Target Corporation", ticker: "TGT" },
    { company: "BlackBerry Limited", ticker: "BB" },
    { company: "Teucrium Corn Fund", ticker: "CORN" },
    { company: "JD.com, Inc.", ticker: "JD" },
    { company: "Square, Inc.", ticker: "SQ" },
    { company: "MP Materials Corp.", ticker: "MP" },
    { company: "CME Group Inc.", ticker: "CME" },
    { company: "Plug Power Inc.", ticker: "PLUG" },
    { company: "BABA", ticker: "Alibaba Group Holding" },
    { company: "Ethan Allen Interiors Inc", ticker: "ETH" },
    { company: "Take-Two Interactive Software Inc", ticker: "TTWO" },
    { company: "The Walt Disney Company", ticker: "DIS" },
    { company: "Facebook, Inc.", ticker: "FB" },
    { company: "CVS HEALTH CORPORATION", ticker: "CVS" },
    { company: "Microvision Inc", ticker: "MVIS" },
    { company: "Microsoft Corp", ticker: "MSFT" },
    { company: "General Electric Company", ticker: "GE" },
    { company: "lululemon athletica inc.", ticker: "LULU" },
    { company: "Chipotle Mexican Grill, Inc.", ticker: "CMG" },
    { company: "Brookfield Asset Management Inc", ticker: "BAM" },
    { company: "DoorDash, Inc. 46", ticker: "DASH" },
    { company: "Rocket Companies, Inc.", ticker: "RKT" },
    { company: "Nikola Corporation Common Stock", ticker: "NKLA" },
    { company: "Amazon.Com Inc", ticker: "AMZN" },
    { company: "Clover Health Investments, Corp", ticker: "CLOV" },
    { company: "ViacomCBS Inc.", ticker: "VIAC" },
    { company: "Cisco Systems, Inc.", ticker: "CSCO" },
    { company: "Tilray, Inc.", ticker: "TLRY" },
    { company: "DocuSign, Inc.", ticker: "DOCU" },
    { company: "Bank of New York Mellon Corporation", ticker: "BK" },
    { company: "General Motors Company", ticker: "GM" },
    { company: "Live Nation Entertainment Inc.", ticker: "LYV" }
]